/**
 * resend-daily-code.ts
 *
 * ONE-OFF script (14 out 2026) — rezanvwaye kòd jounalye admin an pa imel,
 * lè kòd otomatik minwi a (autoGenerateDailyCode, wè admin.service.ts:732)
 * pa t rive. Reyize EGZAKTMAN menm chemen kòd ke cron nòmal la itilize
 * (AdminService.generateDailyCode() + MailService.sendDailyCode()) — jenere
 * yon nouvo kòd, envalide ansyen an, epi voye l bay imel master a ak
 * contact@ozamapay.com. Script la pa janm ekri/afiche valè kòd la;
 * sèl konfimasyon ki parèt se adrès imel yo kòd la te voye bay.
 *
 * Kòmand (nan /backend):
 *   npx ts-node --transpile-only --compiler-options '{"module":"CommonJS","moduleResolution":"node","resolvePackageJsonExports":false}' scripts/one-off/resend-daily-code.ts
 */

import * as dotenv from 'dotenv';
dotenv.config();

import { NestFactory } from '@nestjs/core';
import { Module } from '@nestjs/common';
import { MailModule } from '../../src/mail/mail.module';
import { AdminService } from '../../src/admin/admin.service';
import { MailService } from '../../src/mail/mail.service';
import { PrismaService } from '../../src/prisma/prisma.service';

// Module minimal, sèlman providers — evite AdminController/AdminModule konplè
// ki mande lòt depandans (TrackingService, elatriye) san rapò ak script sa a.
@Module({
  imports: [MailModule],
  providers: [AdminService, PrismaService],
})
class ResendDailyCodeModule {}

async function main() {
  const app = await NestFactory.createApplicationContext(ResendDailyCodeModule, { logger: ['error', 'warn'] });
  const prisma = app.get(PrismaService);
  const adminService = app.get(AdminService);
  const mailService = app.get(MailService);

  try {
    const { expiresAt } = await adminService.generateDailyCode();

    const today = new Date().toLocaleDateString('fr-FR', {
      day: '2-digit', month: 'long', year: 'numeric',
      timeZone: 'America/Port-au-Prince',
    });

    const masterId = process.env.OZAMAPAY_MASTER_ID as string;
    const masterUser = masterId
      ? await prisma.user.findUnique({ where: { id: masterId }, select: { email: true } })
      : null;

    // Re-lire le code (jamais loggé) uniquement pour l'envoi email
    const current = await adminService.getCurrentDailyCode();
    if (!current) throw new Error('Aucun code actif trouvé après génération.');

    const recipients: string[] = [];

    if (masterUser?.email && masterUser.email !== 'contact@ozamapay.com') {
      await mailService.sendDailyCode(masterUser.email, current.code, today, expiresAt);
      recipients.push(masterUser.email);
    }

    await mailService.sendDailyCode('contact@ozamapay.com', current.code, today, expiresAt);
    recipients.push('contact@ozamapay.com');

    await prisma.adminActionLog.create({
      data: {
        adminId: masterId,
        action: 'DAILY_CODE_MANUAL_RESEND',
        targetType: 'DailyAccessCode',
        details: 'Code journalier rezanvwaye manyèlman (script one-off) — kòd otomatik minwi a pa t rive.',
      },
    });

    console.log(`[OK] Nouvo kòd jounalye jenere e voye pa imel bay: ${recipients.join(', ')}`);
    console.log(`[OK] Ekspirasyon: ${expiresAt.toISOString()}`);
    console.log('[OK] Kòd la PA afiche isit — tcheke bwat imel la.');
  } finally {
    await app.close();
  }
}

main().catch((err) => {
  console.error('ERROR', err.message);
  process.exit(1);
});
