services:
  - type: web
    name: ozamapay-backend
    env: node
    rootDir: backend
    autoDeploy: true
    buildCommand: npm ci && npx prisma generate && npm run build && npx prisma migrate deploy && npx prisma db seed
    startCommand: node dist/main
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: OZAMAPAY_MASTER_ID
        sync: false
      - key: BACKEND_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: MONCASH_CLIENT_ID
        sync: false
      - key: MONCASH_SECRET_KEY
        sync: false
      - key: MONCASH_URL
        sync: false
      - key: MONCASH_MODE
        sync: false
      - key: MONCASHCONNECT_PUBLIC_KEY
        sync: false
      - key: MONCASHCONNECT_SECRET_KEY
        sync: false
      - key: MONCASHCONNECT_WEBHOOK_SECRET
        sync: false
      - key: STROWALLET_PUBLIC_KEY
        sync: false
      - key: STROWALLET_SECRET_KEY
        sync: false
      - key: STROWALLET_WEBHOOK_SECRET
        sync: false
      - key: IMAGEKIT_PUBLIC_KEY
        sync: false
      - key: IMAGEKIT_PRIVATE_KEY
        sync: false
      - key: IMAGEKIT_URL_ENDPOINT
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: SENTRY_DSN
        sync: false
      - key: TRON_MASTER_MNEMONIC
        sync: false
      - key: TRONGRID_API_KEY
        sync: false
      - key: TRONGRID_BASE_URL
        sync: false
      - key: USDT_TRC20_CONTRACT_ADDRESS
        sync: false
      - key: USDT_MIN_CONFIRMATIONS
        sync: false
      - key: NODE_ENV
        value: production
