// Behavioral regression tests for the staging cron/loop guards added
// alongside src/config/app-env.ts. Each service is instantiated manually
// (no Nest DI) with a minimal Prisma-shaped mock — the mocked call that
// would be the FIRST thing the real method touches after the guard. If the
// guard is ever removed or short-circuits wrongly, these fail.
import fs from 'fs';
import path from 'path';

const ORIGINAL_ENV = { ...process.env };

afterEach(() => {
  process.env = { ...ORIGINAL_ENV };
  jest.resetModules();
  jest.restoreAllMocks();
});

function setStaging(on: boolean) {
  if (on) process.env.APP_ENV = 'staging';
  else delete process.env.APP_ENV;
}

describe('cron guards — staging blocks, unset APP_ENV behaves exactly like today', () => {
  it('sweep.service.ts scheduledSweepSafetyNet never calls runAutoSweep in staging, always does otherwise', async () => {
    const { SweepService } = require('../tron/sweep.service');
    const runAutoSweep = jest
      .spyOn(SweepService.prototype as any, 'runAutoSweep')
      .mockResolvedValue(null);

    setStaging(true);
    const staging = new SweepService({} as any, {} as any, {} as any);
    await (staging as any).scheduledSweepSafetyNet();
    expect(runAutoSweep).not.toHaveBeenCalled();

    setStaging(false);
    const prod = new SweepService({} as any, {} as any, {} as any);
    await (prod as any).scheduledSweepSafetyNet();
    expect(runAutoSweep).toHaveBeenCalledTimes(1);
  });

  it('moncashconnect.service.ts expireStalePayments never touches the DB in staging, does otherwise', async () => {
    const { MonCashConnectService } = require('../payments/moncashconnect.service');
    const findMany = jest.fn().mockResolvedValue([]);
    const prisma = { transaction: { findMany } } as any;

    setStaging(true);
    await new MonCashConnectService(prisma, {} as any).expireStalePayments();
    expect(findMany).not.toHaveBeenCalled();

    setStaging(false);
    await new MonCashConnectService(prisma, {} as any).expireStalePayments();
    expect(findMany).toHaveBeenCalledTimes(1);
  });

  it('strowallet.service.ts pollPendingCardCreations never touches the DB in staging, does otherwise', async () => {
    const { StrowalletService } = require('../strowallet/strowallet.service');
    const findMany = jest.fn().mockResolvedValue([]);
    const prisma = { cardCreationPending: { findMany } } as any;
    const config = { get: () => undefined } as any;

    setStaging(true);
    await new StrowalletService(prisma, config, {} as any, {} as any, {} as any).pollPendingCardCreations();
    expect(findMany).not.toHaveBeenCalled();

    setStaging(false);
    await new StrowalletService(prisma, config, {} as any, {} as any, {} as any).pollPendingCardCreations();
    expect(findMany).toHaveBeenCalledTimes(1);
  });

  it('admin.service.ts autoGenerateDailyCode never touches the DB in staging, does otherwise', async () => {
    const { AdminService } = require('../admin/admin.service');
    // Resolve as an active pause so the real method returns right after this
    // one call, without needing to mock the full generate+email+log chain.
    const findFirst = jest.fn().mockResolvedValue({ code: 'PAUSED', expiresAt: new Date(Date.now() + 999999) });
    const prisma = { dailyAccessCode: { findFirst } } as any;

    setStaging(true);
    await new AdminService(prisma, {} as any).autoGenerateDailyCode();
    expect(findFirst).not.toHaveBeenCalled();

    setStaging(false);
    await new AdminService(prisma, {} as any).autoGenerateDailyCode();
    expect(findFirst).toHaveBeenCalledTimes(1);
  });

  it('team-meeting-reminder.service.ts sendUpcomingMeetingReminders never touches the DB in staging, does otherwise', async () => {
    const { TeamMeetingReminderService } = require('../team/team-meeting-reminder.service');
    const findMany = jest.fn().mockResolvedValue([]);
    const prisma = { teamCalendarEvent: { findMany } } as any;

    setStaging(true);
    await new TeamMeetingReminderService(prisma, {} as any).sendUpcomingMeetingReminders();
    expect(findMany).not.toHaveBeenCalled();

    setStaging(false);
    await new TeamMeetingReminderService(prisma, {} as any).sendUpcomingMeetingReminders();
    expect(findMany).toHaveBeenCalledTimes(1);
  });

  it('health.service.ts checkHealth never queries the DB in staging, does otherwise', async () => {
    const { HealthService } = require('../health/health.service');
    const queryRaw = jest.fn().mockResolvedValue([{ 1: 1 }]);
    const prisma = { $queryRaw: queryRaw } as any;

    setStaging(true);
    await new HealthService(prisma, {} as any).checkHealth();
    expect(queryRaw).not.toHaveBeenCalled();

    setStaging(false);
    await new HealthService(prisma, {} as any).checkHealth();
    expect(queryRaw).toHaveBeenCalledTimes(1);
  });

  it('tron-monitor.service.ts onModuleInit never starts the perpetual loop in staging, does otherwise', () => {
    const { TronMonitorService } = require('../tron/tron-monitor.service');
    const runForever = jest
      .spyOn(TronMonitorService.prototype as any, 'runForever')
      .mockResolvedValue(undefined);

    setStaging(true);
    new TronMonitorService({} as any, {} as any, {} as any, {} as any).onModuleInit();
    expect(runForever).not.toHaveBeenCalled();

    setStaging(false);
    new TronMonitorService({} as any, {} as any, {} as any, {} as any).onModuleInit();
    expect(runForever).toHaveBeenCalledTimes(1);
  });
});

// The remaining guarded crons (bsicards-balance-sync, ziiropay-correlation,
// rates, card-termination, reconciliation, tron-health,
// admin.resumeDailyCodeAfterPause) share constructors heavy enough that a
// full behavioral mock isn't worth it here — instead assert the exact guard
// snippet is still present as the first statement of each method body, so a
// future edit can't silently drop it without failing CI.
describe('cron guards — static presence check for the rest of the guarded list', () => {
  const SRC = path.join(__dirname, '..');

  const expectations: Array<{ file: string; method: string }> = [
    { file: 'bsicards/bsicards-balance-sync.service.ts', method: 'syncAllBalances' },
    { file: 'strowallet/ziiropay-correlation.service.ts', method: 'checkPending' },
    { file: 'rates/rates.service.ts', method: 'checkRateStaleness' },
    { file: 'strowallet/card-termination.service.ts', method: 'retryPendingRecharges' },
    { file: 'tron/reconciliation.service.ts', method: 'scheduledReconciliation' },
    { file: 'tron/tron-health.service.ts', method: 'scheduledHealthCheck' },
    { file: 'admin/admin.service.ts', method: 'resumeDailyCodeAfterPause' },
  ];

  it.each(expectations)('$file :: $method() guards on isStaging() before any other statement', ({ file, method }) => {
    const source = fs.readFileSync(path.join(SRC, file), 'utf8');
    const methodStart = source.indexOf(`${method}(`);
    expect(methodStart).toBeGreaterThan(-1);
    const bodyAfter = source.slice(methodStart, methodStart + 400);
    const guardIdx = bodyAfter.indexOf('isStaging()');
    const returnIdx = bodyAfter.indexOf('return;');
    expect(guardIdx).toBeGreaterThan(-1);
    expect(returnIdx).toBeGreaterThan(guardIdx);
  });
});
